// This file was automatically generated from templates.soy.
// Please don't edit this file by hand.

if (typeof templates == 'undefined') { var templates = {}; }


templates.collective = function(opt_data, opt_ignored) {
  return '\t\t<table><tr><td class="collective-metric-column"><h2> Intensity Level Synchrony </h2></td><td class="collective-metric-column"><h2> Intensity Variation Synchrony</h2></td><td class="collective-metric-column"><h2> Rhythmic Business Synchrony</h2></td><td class="collective-metric-column"><h2> Rhythmic Variation Synchrony</h2></td><td class="collective-metric-column"><h2> Melodic Business Synchrony</h2></td><td class="collective-metric-column"><h2> Melodic Variation Synchrony</h2></td><td class="collective-metric-column"><h2> Pattern Synchrony</h2></td><td class="collective-metric-column"><h2> Articulation Synchrony</h2></td></tr><tr><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-il\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-iv\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-rb\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-rv\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-mb\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-mv\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-p\'></div></center></td><td class=\'collective-metric-container\'><center><div class=\'collective-metric\' id=\'collective-a\'></div></center></td></tr></table>';
};


templates.musician = function(opt_data, opt_ignored) {
  var output = '\t<table class="musician-history" style="width:100%">';
  var noteList6 = opt_data.history;
  var noteListLen6 = noteList6.length;
  for (var noteIndex6 = 0; noteIndex6 < noteListLen6; noteIndex6++) {
    var noteData6 = noteList6[noteIndex6];
    output += '<tr><td class="label">Mode</td><td class="value">' + soy.$$escapeHtml(noteData6.mode) + '</td><td class="label">Note</td><td class="value">' + soy.$$escapeHtml(noteData6.note_num) + '</td><td class="label">Octave</td><td class="value">' + soy.$$escapeHtml(noteData6.octave) + '</td><td class="label">Velocity</td><td class="value">' + soy.$$escapeHtml(noteData6.velocity) + '</td><td class="label">Action</td><td class="value">' + soy.$$escapeHtml(noteData6.action) + '</td><td class="label">Time</td><td class="value">' + soy.$$escapeHtml(noteData6.timestamp) + '</td></tr>';
  }
  output += '</table><div class="separator"> </div><table><tr><td class="individual-metric-column"><h2> Intensity Level </h2></td><td class="individual-metric-column"><h2> Intensity Variation </h2></td><td class="individual-metric-column"><h2> Rhythmic Business </h2></td><td class="individual-metric-column"><h2> Rhythmic Variation </h2></td><td class="individual-metric-column"><h2> Melodic Business </h2></td><td class="individual-metric-column"><h2> Melodic Variation </h2></td><td class="individual-metric-column"><h2> Pattern </h2></td><td class="individual-metric-column"><h2> Articulation </h2></td></tr><tr><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-intensity-level\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-intensity-variation\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-rhythmic-business\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-rhythmic-variation\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-melodic-business\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-melodic-variation\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-pattern\'></div></td><td class=\'individual-metric-container\'><div class=\'individual-metric\' id=\'m' + soy.$$escapeHtml(opt_data.number) + '-articulation\'></div></td></tr></table><div class="separator"> </div><table><tr><td class="feedback-label"><h2> Heat </h2></td><td class="feedback-label"><h2> Vibration </h2></td><td class="feedback-label"><h2> Cold </h2></td></tr><tr><td class="feedback-indicator"><center><div class="feedback" id="feedback-m' + soy.$$escapeHtml(opt_data.number) + '-hot"></div></center></td><td class="feedback-indicator"><center><div class="feedback" id="feedback-m' + soy.$$escapeHtml(opt_data.number) + '-vib"></div></center></td><td class="feedback-indicator"><center><div class="feedback" id="feedback-m' + soy.$$escapeHtml(opt_data.number) + '-cold"></div></center></td></tr></table>';
  return output;
};


templates.systemStatus = function(opt_data, opt_ignored) {
  return '\t<table style="width:100%"><tr><td class="status-label">Biometric Feedback</td><td class="status-label">Midi Keyboard</td><td class="status-label">Production Control</td><td class="status-label">Audience Visuals</td><td class="status-label">Synchronization</td></tr><tr><td class="status"><center><div class="status-indicator" id="biometric"> </div></center></td><td class="status"><center><div class="status-indicator" id="midi"> </div></center><td class="status"><center><div class="status-indicator" id="production" style="background-color: \'green\';"> </div></center></td><td class="status"><center><div class="status-indicator" id="audience"> </div></center></td><td class="status"><center><div class="status-indicator" id="sync"> </div></center></td></tr></table>';
};
